version: '3.8'

services:
  web:
    build: .
    expose:
      - "5004"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  redis:
      image: redis:latest
      platform: linux/arm64/v8
      ports:
        - "6379:6379"
      volumes:
        - redis-data:/data

  nginx:
    image: nginx:latest
    ports:
      - "5004:5004"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web

    
volumes:
  redis-data:
